In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('student_dropout_dataset_v3.csv')

In [5]:
df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [6]:
df.drop_duplicates()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,23.9,Female,42286.0,No,4.62,92.0,0,10.0,Yes,Yes,5.5,1.60,0.99,0.97,Year 2,Arts,Bachelor,0
9996,9997,17.0,Female,61103.0,Yes,2.87,75.2,3,32.4,No,Yes,6.7,3.09,3.09,3.09,Year 1,Business,Master,1
9997,9998,19.4,Male,25000.0,Yes,4.73,74.9,4,25.4,No,No,3.5,3.45,3.37,3.43,Year 4,Business,Bachelor,0
9998,9999,22.1,Female,40302.0,Yes,5.85,74.2,1,5.0,No,Yes,6.2,3.35,3.34,3.34,Year 1,CS,High School,0
9999,10000,22.4,Female,76796.0,Yes,4.95,83.7,1,15.5,Yes,No,7.9,2.17,2.20,2.20,Year 1,Arts,Master,0

In [7]:
df.describe()

,Student_ID,Age,Family_Income,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Stress_Index,GPA,Semester_GPA,CGPA,Dropout
count,10000.00000,10000.00000,9500.000000,9500.000000,10000.00000,10000.000000,10000.00000,9500.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,21.02606,38377.247474,4.014592,81.73683,1.799700,30.17926,5.507147,2.308440,2.300057,2.298761,0.23540
std,2886.89568,2.13981,20496.232179,1.295450,8.22093,1.344307,11.91887,1.765951,1.061717,1.074407,1.072555,0.42427
min,1.00000,17.00000,25000.000000,0.500000,38.20000,0.000000,5.00000,1.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,19.50000,25000.000000,3.160000,76.40000,1.000000,21.90000,4.300000,1.550000,1.520000,1.520000,0.00000
50%,5000.50000,21.00000,29740.500000,4.000000,81.80000,2.000000,30.20000,5.500000,2.350000,2.350000,2.350000,0.00000
75%,7500.25000,22.50000,44520.000000,4.870000,87.30000,3.000000,38.40000,6.700000,3.120000,3.150000,3.150000,0.00000
max,10000.00000,29.60000,316601.000000,8.980000,100.00000,8.000000,74.90000,10.000000,4.000000,4.000000,4.000000,1.00000

In [8]:
df.isnull().mean() * 100

Student_ID               0.00
Age                      0.00
Gender                   0.00
Family_Income            5.00
Internet_Access          0.00
Study_Hours_per_Day      5.00
Attendance_Rate          0.00
Assignment_Delay_Days    0.00
Travel_Time_Minutes      0.00
Part_Time_Job            0.00
Scholarship              0.00
Stress_Index             5.00
GPA                      0.00
Semester_GPA             0.00
CGPA                     0.00
Semester                 0.00
Department               0.00
Parental_Education       5.11
Dropout                  0.00
dtype: float64

In [9]:
# As we can see, the percentage of missing values in some columns are almost all less than or equal to 5%.  
# Therefore, filling them with median or mode is more better way to keep all valuable data rather than just droppig
# the rows

In [10]:
df['Parental_Education'] = df['Parental_Education'].fillna('Unknown')

In [11]:
df['Parental_Education'].value_counts()

Parental_Education
Bachelor       3949
High School    3072
Master         2003
Unknown         511
PhD             465
Name: count, dtype: int64

In [12]:
# I filled none values in Parental Education with 'Unknown' since this column only stored categorical data.

In [13]:
fam_inc_med = df.groupby('Parental_Education')['Family_Income'].transform('median')
df['Family_Income'] = df['Family_Income'].fillna(fam_inc_med)

In [14]:
df['Family_Income'].isnull().sum()

np.int64(0)

In [15]:
# I filled the missing values in Family income using meadians of each subgroups within Parental Education.
#  As result, we have appropraite data since the income is positive corelated to education level in more cases.
# Using median helps us fill the null values without any high-income outliers' effect

In [16]:
sts_inx_rate = df.groupby(['Part_Time_Job','Scholarship'])['Stress_Index'].transform('median')

In [17]:
df['Stress_Index'] = df['Stress_Index'].fillna(sts_inx_rate)

In [18]:
df['Stress_Index'].isnull().sum()

np.int64(0)

In [19]:
df[['Scholarship' ,'Part_Time_Job', 'Stress_Index']]

     Scholarship Part_Time_Job  Stress_Index
0             No           Yes           5.5
1             No            No           6.8
2             No           Yes           5.5
3             No            No           5.6
4             No            No           7.0
...          ...           ...           ...
9995         Yes           Yes           5.5
9996         Yes            No           6.7
9997          No            No           3.5
9998         Yes            No           6.2
9999          No           Yes           7.9

[10000 rows x 3 columns]

In [20]:
df['Stress_Index'].isnull().sum()

np.int64(0)

In [21]:
# Filled missing Stress_Index values using median scores grouped by Scholarship and Part_Time_Job
# status to get more appropriate, context-specific estimates.

In [22]:
df.isnull().mean()*100

Student_ID               0.0
Age                      0.0
Gender                   0.0
Family_Income            0.0
Internet_Access          0.0
Study_Hours_per_Day      5.0
Attendance_Rate          0.0
Assignment_Delay_Days    0.0
Travel_Time_Minutes      0.0
Part_Time_Job            0.0
Scholarship              0.0
Stress_Index             0.0
GPA                      0.0
Semester_GPA             0.0
CGPA                     0.0
Semester                 0.0
Department               0.0
Parental_Education       0.0
Dropout                  0.0
dtype: float64

In [23]:
df['Study_Hours_per_Day'] = pd.to_numeric(df['Study_Hours_per_Day'] , errors='coerce' )
study_hour_pd = df.groupby(['Gender', 'Internet_Access', 'Part_Time_Job', 'Scholarship', 'Department'])['Study_Hours_per_Day'].transform('median')
df['Study_Hours_per_Day']=df['Study_Hours_per_Day'].fillna(study_hour_pd)

In [24]:
# Filled missing Study_Hours_per_Day values using median scores grouped by Gender, Internet_Access, Scholarship, Part_Time_Job and Department
# status to get more appropriate, context-specific estimates.
# I believe that these subgroups can help us to estimate with more accuracy

In [25]:
df.to_csv('student_drop_out_new_dataset.csv', index= False)

In [26]:
df.isnull().mean()*100

Student_ID               0.0
Age                      0.0
Gender                   0.0
Family_Income            0.0
Internet_Access          0.0
Study_Hours_per_Day      0.0
Attendance_Rate          0.0
Assignment_Delay_Days    0.0
Travel_Time_Minutes      0.0
Part_Time_Job            0.0
Scholarship              0.0
Stress_Index             0.0
GPA                      0.0
Semester_GPA             0.0
CGPA                     0.0
Semester                 0.0
Department               0.0
Parental_Education       0.0
Dropout                  0.0
dtype: float64

In [27]:
# Now, we have cleaned data and we can use it for analysis

In [28]:
type(df)

pandas.core.frame.DataFrame